### ISSUE TITLE
Failing tests Python 3.5 MessagePack (question/bug)

### ISSUE THREAD

**Issue by lyschoening** [aio-libs/aiozmq#64]
I just came across this package and it looks very promising, but I can see that the last push was five months ago and some of the Python 3.5 tests using MessagePack failed. Is this package still being maintained?

**Comment by jettify** [comment]
Hi, thank you for raising this issue! Package is maintained. Those errors you are seeing most likely because error message we expect in tests  was changed somewhere, see:
```
AssertionError: "TypeError.*'arg' parameter lacking default value" does not match 
"TypeError("missing a required argument: 'arg'",)"
```

probably related to this python patch:
https://bugs.python.org/file39422/sig_exc.patch

Would you like to create PR to for a fix? Otherwise I can do that today.

cc @asvetlov @popravich
