### ISSUE TITLE
PUB/SUB inexplicable behaviour

### ISSUE THREAD

**Issue by mihu** [aio-libs/aiozmq#88]
Hi, today I've run into some hard to explain behavior of test program. Not sure if it's bug in my code, the aiozmq or zmq itself. Two samples of code below shows two correct scenarios. First of them uses inproc transport and connects client before binding server. The second one uses tcp transport and binds server before connecting the client.

If I change the ordering in those two scenarios the program will freeze on read (published message will get lost).

* aiozmq: 0.7.1
* pyzmq: 15.4.0
* zmq: 4.2.0

```python
import aiozmq
import asyncio
import zmq

@asyncio.coroutine
def go():
    _pubsub = 'inproc://pubsub'

    client = yield from aiozmq.create_zmq_stream(zmq.SUB, connect=_pubsub)
    server = yield from aiozmq.create_zmq_stream(zmq.PUB, bind=_pubsub)

    client.transport.subscribe(b'')

    yield from asyncio.sleep(0.1)

    server.write([b'hello world'])
    yield from asyncio.sleep(0.1)
    msg = yield from client.read()
    print(msg)

    server.close()
    client.close()

asyncio.get_event_loop().run_until_complete(go())
```
```python
import aiozmq
import asyncio
import zmq

@asyncio.coroutine
def go():
    _pubsub = 'tcp://127.0.0.1:6666'

    server = yield from aiozmq.create_zmq_stream(zmq.PUB, bind=_pubsub)
    client = yield from aiozmq.create_zmq_stream(zmq.SUB, connect=_pubsub)

    client.transport.subscribe(b'')

    yield from asyncio.sleep(0.1)

    server.write([b'hello world'])
    yield from asyncio.sleep(0.1)
    msg = yield from client.read()
    print(msg)

    server.close()
    client.close()

asyncio.get_event_loop().run_until_complete(go())
```

**Comment by asvetlov** [comment]
It's described ZMQ behavior.

**Comment by quantumkoen** [comment]
Sorry to respond to such an old issue, but we're hitting this same issue and wondering where this behavior is described.

**Comment by mihu** [comment]
Don't remember what exactly was the initial problem (my earlier explanation is even confusing for me now), but I think you might be looking for the [inproc server must issue a bind before any client issues a connect](http://zguide.zeromq.org/page:all#Unicast-Transports).

**Comment by quantumkoen** [comment]
@mihu thanks, that indeed describes the case for inproc - for tcp they say 'ZeroMQ's tcp transport doesn't require that the endpoint exists before you connect to it. Clients and servers can connect and bind at any time, can go and come back, and it remains transparent to applications'. However when using aiozmq and tcp sockets, your program above is indeed sensitive to the order of creating the zmq streams. So when the streams are both created in the same process, the order matters. When running the server and client in seperate processes (still using aiozmq) it doesn't matter in which order you start things though, it will work either way.

It's not a big deal for our current application, as we use zmq for communication between processes. However, it is an inconvenience when unit-testing, because then we tend to do things in a single process. I'm still curious to learn where zmq describes this behaviour for tcp sockets.
